name: smri2dwi
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=openblas
  - blosc=1.20.1=hd408876_0
  - bzip2=1.0.8=h516909a_3
  - ca-certificates=2020.12.5=ha878542_0
  - cached-property=1.5.1=py_0
  - cairo=1.16.0=h9f066cc_1006
  - certifi=2020.12.5=py38h578d9bd_1
  - cudatoolkit=10.1.243=h6bb024c_0
  - cvxopt=1.2.5=py38hf48cded_2
  - cycler=0.10.0=py_2
  - dbus=1.13.6=hfdff14a_1
  - decorator=4.4.2=py_0
  - dipy=1.3.0=py38h0b5ebd8_0
  - dsdp=5.8=hd9d9efa_1203
  - eigen=3.3.9=h4bd325d_1
  - expat=2.2.10=h9c3ff4c_0
  - ffmpeg=4.3.1=hca11adc_2
  - fftw=3.3.8=nompi_hfc0cae8_1114
  - fontconfig=2.13.1=hba837de_1004
  - freetype=2.10.4=h7ca028e_0
  - gettext=0.19.8.1=h0b5b191_1005
  - glib=2.66.7=h9c3ff4c_0
  - glib-tools=2.66.7=h9c3ff4c_0
  - glpk=4.65=h9202a9a_1003
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.6=hf94e986_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.18.3=h3560a44_0
  - h5py=3.1.0=nompi_py38hafa665b_100
  - harfbuzz=2.7.2=ha5b49bf_1
  - hdf5=1.10.6=nompi_h3c11f04_101
  - icu=67.1=he1b5a44_0
  - intel-openmp=2020.2=254
  - ipython=7.20.0=py38h81c977d_2
  - ipython_genutils=0.2.0=py_1
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.18.0=py38h578d9bd_2
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py38h82cb98a_0
  - krb5=1.17.2=h926e7f8_0
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libclang=11.0.1=default_ha53f305_1
  - libedit=3.1.20191231=h14c3975_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=7.5.0=h14aa051_18
  - libgfortran4=7.5.0=h14aa051_18
  - libglib=2.66.7=h1f3bc88_0
  - libgomp=9.3.0=h2828fa1_18
  - libiconv=1.16=h516909a_0
  - libitk=5.1.2=h86d312b_0
  - libitk-devel=5.1.2=h9c3ff4c_0
  - liblapack=3.9.0=8_openblas
  - liblapacke=3.9.0=8_openblas
  - libllvm11=11.0.1=hf817b99_0
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libopencv=4.5.1=py38h703c3c0_0
  - libpng=1.6.37=h21135ba_2
  - libpq=12.3=h255efa7_3
  - libprotobuf=3.14.0=h8c45485_0
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.2.0=hdc55705_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.0=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.10=h68273f3_2
  - lz4-c=1.9.2=he1b5a44_3
  - lzo=2.10=h516909a_1000
  - matplotlib-base=3.2.2=py38h5d868c9_1
  - metis=5.1.0=h58526e2_1006
  - mkl=2020.2=256
  - mock=4.0.3=py38h578d9bd_1
  - mysql-common=8.0.22=ha770c72_1
  - mysql-libs=8.0.22=h1fd7589_1
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - nibabel=3.2.1=pyhd8ed1ab_0
  - ninja=1.10.2=py38hff7bd54_0
  - nspr=4.29=h9c3ff4c_1
  - nss=3.61=hb5efdd6_0
  - numexpr=2.7.2=py38h4be448d_0
  - numpy=1.18.1=py38h8854b6b_1
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.1=py38h578d9bd_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1j=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.2=py38h51da96c_0
  - parso=0.8.1=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=6.2.1=py38h6b7be26_0
  - pip=20.3.3=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - prompt-toolkit=3.0.16=pyha770c72_0
  - protobuf=3.14.0=py38h2531618_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-opencv=4.5.1=py38h81c977d_0
  - pydicom=2.1.2=pyhd3deb0d_0
  - pygments=2.8.0=pyhd8ed1ab_0
  - pynrrd=0.4.2=pyh95af2a2_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pytables=3.6.1=py38hf9f05d5_3
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.4.0=py3.8_cuda10.1.243_cudnn7.6.3_0
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.3.1=py38h8df0ef7_1
  - qt=5.12.9=h763d07f_1
  - readline=8.1=h27cfd23_0
  - scikit-learn=0.23.2=py38h5d63f67_3
  - scipy=1.5.3=py38h828c644_0
  - seaborn=0.11.1=hd8ed1ab_1
  - seaborn-base=0.11.1=pyhd8ed1ab_1
  - setuptools=52.0.0=py38h06a4308_0
  - simpleitk=2.0.2=py38hb8ccc7d_1
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.34.0=h74cdb3f_0
  - statsmodels=0.12.2=py38h5c078b8_0
  - suitesparse=5.7.2=h717dc36_0
  - tbb=2020.2=hc9558a2_0
  - tensorboardx=2.1=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - time=1.8=h516909a_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.4.0=py38
  - torchvision=0.5.0=py38_cu101
  - tornado=6.1=py38h25fe258_0
  - tqdm=4.56.2=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0


